openapi: "3.0.0"
info:
  title: Pratyaksh
  description: A realtime infrastructure monitoring software
  version: 0.1.1
servers:
  - url: http://localhost:5000/api/v1
    description: Testing server

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

tags:
  - name: users
    description: Operations related to user management

paths:
  /signup:
    post:
      summary: SignUp a new user.
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User signup successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                      email:
                        type: string
        '400':
          description: Bad Request
        '500':
          description: Internal server error

  /login:
    post:
      summary: User Login
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
        '400':
          description: Bad Request
        '500':
          description: Internal server error

  /logout:
    get:
      summary: User logout
      tags:
        - users
      responses:
        '200':
          description: Successful Logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /changePassword:
    post:
      summary: Change Password
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - oldPassword
                - newPassword
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Password changes successfully
          content:
            application/json:
              schema:
                type: object  
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
        '400':
          description: Bad Request
        '500':
          description: Internal server error
         
  /updateUser:
    put:
      summary: Update User
      tags: 
        - users
      responses:
        '200':
          description: Successfully Updated User
          content:
            application/json:
              schema:
                type: object
                required:
                  - currentProject
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error    

  /removeUserFromProject:
    get:
      summary: Remove User From Project
      tags:
        - users
      responses:
        '200':
          description: Successfully Removed User
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error 
  
  /addProject:
    post:
      summary: Add Project
      tags:
        - projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Added Project Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
        '400':
          description: Bad Request
        '500':
          description: Internal server error
 
  /getOneProject: 
    get:
        summary: Get One project
        tags:
          - projects
        parameters:
          - name: projectId
            in: url
            description: The unique identifier of the project.
            required: true
            schema:
              type: string
        responses:
        '200':
          description: Successfully Retrieved Project
          content:     
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  project:
                    type: object
                    properties:
                      location:
                        type: object
                        properties:
                          coordinates:
                            type: array
                            items: {} # You need to define the structure of coordinates if applicable
                      _id:
                        type: string
                      name:
                        type: string
                      status:
                        type: string
                      user:
                        type: string
                      milestones:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            status:
                              type: string
                            tasks:
                              type: array
                              items:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  description:
                                    type: string
                                  dueDate:
                                    type: string
                                    format: date-time
                                  assigned:
                                    type: string
                                  priority:
                                    type: string
                                  status:
                                    type: string
                                  _id:
                                    type: string
                            _id:
                              type: string
                      __v:
                        type: integer
                  updatedUser:
                    type: object
                    properties:
                      _id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      password:
                        type: string
                      role:
                        type: string
                      currentProject:
                        type: string
                      projects:
                        type: array
                        items:
                          type: string
                      __v:
                        type: integer
                  
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /getAllProjectOfUser:
    get:
      summary: Get All Project Of User 
      tags:
        - projects
      responses:
        '200':
          description: Successfully retrieved all projects
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /getAllUsersOfProject:
    get:
      summary: Get All Users Of Project 
      tags:
        - users
      responses:
        '200':
          description: Successful Logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error  
    
  /updateProject:
    put:
      summary: Update Project
      tags: 
        - projects
      responses:
        '200':
          description: Successfully Updated Project
          content:
            application/json:
              schema:
                type: object
                required:
                  - currentProject
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
  /getAllProject: 
    get:
      summary: Get All Projects
      tags:
        - projects
      responses:
        '200':
          description: Successfully retrieved all projects
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error  

  /addProjectUpdate:
    post:
      summary: Add Project Update
      tags:
        - updateProjects
      requestBody:
        required: true
        content:
          application/json:
             schema:
              type: object
              properties:
                description:
                  type: string
                progressPercentage:
                  type: integer
                externalFactors:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      description:
                        type: string
                      impact:
                        type: string
                      severity:
                        type: string
      responses:
        '200':
          description: Project update added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  schema:
                  type: object
                  properties:
                    projectId:
                      type: string
                    userId:
                      type: string
                    updateDate:
                      type: string
                      format: date-time
                    progressPercentage:
                      type: integer
                    externalFactors:
                      type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        description:
                          type: string
                        impact:
                          type: string
                        severity:
                          type: string
                        _id:
                          type: string
                  _id:
                    type: string
                  __v:
                    type: integer
        '400':
          description: Bad Request
        '500':
          description: Internal server error

  /getAllUpdatesOfProject:
     get:
      summary: Get All Updates Of Project
      tags:
        - updateProjects
      responses:
        '200':
          description: Successfully retrieved data of projects
          content:
            application/json:
              schema:
                type: object
                properties:
                  schema:
                  type: object
                  properties:
                    projectId:
                      type: string
                    userId:
                      type: string
                    updateDate:
                      type: string
                      format: date-time
                    progressPercentage:
                      type: integer
                    externalFactors:
                      type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        description:
                          type: string
                        impact:
                          type: string
                        severity:
                          type: string
                        _id:
                          type: string
                  __v:
                    type: integer
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
             
